# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2f8ed5df0f700145b17905bb2ff69132"
name = "DISCOUNT"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products , write_discounts,read_products"

[[access_scopes.metafields]]
namespace = "custom"
key = "special-discount-configuration"
owner_type = "discount"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
[discount.metafields.custom.special-discount-configuration]
type = "json"
name = "Function configuration"
access.admin = "merchant_read_write"
access.storefront = "none"
